apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
spec:
  project: default
  source:
    repoURL: https://github.com/abirelhajahmed/Gitops-project.git
    path: monitoring/.
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
    createNamespace: true  # ArgoCD will create the 'monitoring' namespace if it doesn't exist
  syncPolicy:
    automated:
      prune: true
      selfHeal: true  # Enable self-healing for the monitoring stack




